### ISSUE TITLE
Path expressions

### ISSUE THREAD

**Issue by maximelefrancois86** [blake-regalia/linked-data.syntaxes#13]
From SPARQL Generation rule [89]  

Should be possible to paths made of alternatives between more than two predicates

``` 
?class (rdfs:comment|prov:definition|skos:definition |obo:IAO_0000115) ?comment
```

replace 

```
  pathAlternative_AFTER_SEQUENCE:
    - meta_include_prototype: false
    - match: '\|'
      scope: keyword.operator.path.alternative.rq
      set: pathSequence
    - include: else_pop
```

to 

```
  pathAlternative_AFTER_SEQUENCE:
    - match: '\|'
      scope: keyword.operator.path.alternative.rq
      set: path
    - include: else_pop
```

also, spaces should be possible between the predicate and the pipe. 
more generally, all the `- meta_include_prototype: false` should be deleted from the path definition

```
SELECT * {
  <> <sdf> | ^ (  <sdgnn> / ^ ! <dqsf>  ) <>
}
```

For pathMod, KEYWORD_BOUNDARY needs to be checked after symbols to not interfere with the possibility of having a variable after the path

```
  pathMod:
    # - meta_include_prototype: false
    - match: '\?{{KEYWORD_BOUNDARY}}'
      scope: keyword.operator.path.quantifier.zero-or-one.rq
    - match: '\*{{KEYWORD_BOUNDARY}}'
      scope: keyword.operator.path.quantifier.zero-or-more.rq
    - match: '\+{{KEYWORD_BOUNDARY}}'
      scope: keyword.operator.path.quantifier.one-or-more.rq
    - include: else_pop
```

few typo:

Production rule [83]  line 1217-1218  solved with 

```
    - match: '{{verbPathOrSimple_LOOKAHEAD}}'
      set: [propertyListPathNotEmpty_AFTER_OBJECT_LIST_PATH, objectList, verbPathOrSimple] 
```

Production rule [90]  line 1256 solved with 

```
      push: pathSequence
```

Production rule [86]  line 1239 solved with 

``` 
      push: objectListPath
``` 

Production rule [79] solved with line 173 in terse.sublime-syntax-source

```
      push: objectList
```
